name: Run Python Script

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Optional: Run on schedule
  # schedule:
  #   - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Python script
      run: python ap.py  # Replace with your script name
